#!/bin/sh

if [ -n $R]; then
	R="/usr/local/bin/R"
else
	R="R"
fi

/bin/rm -rf tmp
mkdir tmp
cp -r lolog tmp/lolog
rm -rf tmp/lolog/Debug
rm -rf tmp/lolog/.cproject
rm -rf tmp/lolog/.project
rm -f tmp/lolog/mkdist
rm -rf tmp/lolog/.git
rm -f tmp/lolog/.gitignore 
rm -rf tmp/lolog/.settings 
mkdir tmp/lolog/inst/include
cp -rf tmp/lolog/src/*\.h tmp/lolog/inst/include
cp -rf tmp/lolog/src/tests/* tmp/lolog/src
rm -rf tmp/lolog/src/tests
rm -f tmp/lolog/src/*.o
rm -f tmp/lolog/src/*.so
rm -rf tmp/lolog/inst/examplePackage/LologExtension/\.*

if [ "$1" == "build" ]; then
  $R CMD build  --no-build-vignettes tmp/lolog
  rm -rf tmp
  exit
fi

if [ "$1" == "check" ]; then
  $R CMD build  --no-build-vignettes tmp/lolog
  $R CMD check --as-cran lolog_1.0.tar.gz
  rm -rf tmp
  exit
fi

if [ "$1" == "quick" ]; then
  $R CMD build  --no-build-vignettes tmp/lolog
else
  $R CMD build  tmp/lolog
fi

rm -rf tmp

if [ "$1" == "quick" ]; then
  $R CMD INSTALL --no-multiarch lolog_1.0.tar.gz
else
  $R CMD INSTALL lolog_1.0.tar.gz
fi
